import type { Shader } from "@/types/shader"
import { getShaderCode } from "./shader-codes"

export const shaders: Shader[] = [
  {
    slug: "liquid-metal",
    name: "Liquid Metal",
    description: "Metallic surface with reflections, fresnel effects, and organic distortions.",
    tags: ["metallic", "reflective", "dark", "abstract"],
    author: "ShaderDrop",
    createdAt: "2025-01-16",
    uniforms: [
      { name: "baseColor", label: "Base Color", type: "color", default: "#1a1a2e" },
      { name: "highlightColor", label: "Highlight", type: "color", default: "#ffffff" },
      { name: "speed", label: "Animation Speed", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
      { name: "scale", label: "Scale", type: "range", default: 1, min: 0.5, max: 2, step: 0.1 },
      { name: "distortion", label: "Distortion", type: "range", default: 1, min: 0.2, max: 2, step: 0.1 },
      { name: "reflectivity", label: "Reflectivity", type: "range", default: 1.5, min: 0.5, max: 3, step: 0.1 },
      { name: "lightIntensity", label: "Light Intensity", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
      { name: "fresnelStrength", label: "Fresnel", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
    ],
    get code() { return getShaderCode("liquid-metal") },
    defaultProps: { baseColor: "#1a1a2e", highlightColor: "#ffffff", speed: 1, scale: 1, distortion: 1, reflectivity: 1.5, lightIntensity: 1, fresnelStrength: 1 },
  },
  {
    slug: "neon-horizon",
    name: "Neon Horizon",
    description: "Synthwave grid with glowing sun and horizon reflections.",
    tags: ["retro", "synthwave", "neon", "80s", "grid"],
    author: "ShaderDrop",
    createdAt: "2025-01-16",
    uniforms: [
      { name: "skyColor1", label: "Sky Dark", type: "color", default: "#0a0015" },
      { name: "skyColor2", label: "Sky Light", type: "color", default: "#1a0030" },
      { name: "gridColor", label: "Grid Color", type: "color", default: "#ff00ff" },
      { name: "sunColor", label: "Sun Color", type: "color", default: "#ffaa00" },
      { name: "speed", label: "Animation Speed", type: "range", default: 1, min: 0.1, max: 2, step: 0.1 },
      { name: "gridSpeed", label: "Grid Speed", type: "range", default: 1, min: 0.3, max: 3, step: 0.1 },
      { name: "sunSize", label: "Sun Size", type: "range", default: 1, min: 0.5, max: 1.5, step: 0.1 },
      { name: "glowIntensity", label: "Glow Intensity", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
    ],
    get code() { return getShaderCode("neon-horizon") },
    defaultProps: { skyColor1: "#0a0015", skyColor2: "#1a0030", gridColor: "#ff00ff", sunColor: "#ffaa00", speed: 1, gridSpeed: 1, sunSize: 1, glowIntensity: 1 },
  },
  {
    slug: "voronoi",
    name: "Voronoi Cells",
    description: "Organic cell pattern with glowing edges, energy flow, and RGB split effect.",
    tags: ["organic", "cells", "sci-fi", "animated", "pattern"],
    author: "ShaderDrop",
    createdAt: "2025-01-16",
    uniforms: [
      { name: "color1", label: "Cell Color 1", type: "color", default: "#1a1a3e" },
      { name: "color2", label: "Cell Color 2", type: "color", default: "#2d1b4e" },
      { name: "edgeColor", label: "Edge Glow", type: "color", default: "#00ffff" },
      { name: "speed", label: "Animation Speed", type: "range", default: 1, min: 0.1, max: 2, step: 0.1 },
      { name: "scale", label: "Cell Count", type: "range", default: 5, min: 3, max: 10, step: 0.5 },
      { name: "edgeWidth", label: "Edge Width", type: "range", default: 0.05, min: 0.02, max: 0.15, step: 0.01 },
      { name: "glowIntensity", label: "Glow Intensity", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
      { name: "energyFlow", label: "Energy Flow", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
      { name: "cellDepth", label: "3D Depth", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
      { name: "movement", label: "Cell Movement", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
      { name: "rgbSplit", label: "RGB Split", type: "range", default: 0.5, min: 0, max: 2, step: 0.1 },
    ],
    get code() { return getShaderCode("voronoi") },
    defaultProps: { color1: "#1a1a3e", color2: "#2d1b4e", edgeColor: "#00ffff", speed: 1, scale: 5, edgeWidth: 0.05, glowIntensity: 1, energyFlow: 1, cellDepth: 1, movement: 1, rgbSplit: 0.5 },
  },
  {
    slug: "pixel-art",
    name: "Retro Sunset",
    description: "Pixel art ocean scene with animated sunset, waves, boats, and shooting stars.",
    tags: ["retro", "pixel", "sunset", "ocean", "landscape", "8bit"],
    author: "ShaderDrop",
    createdAt: "2025-01-16",
    uniforms: [
      { name: "skyColor1", label: "Sky Dark", type: "color", default: "#1a0533" },
      { name: "skyColor2", label: "Sky Light", type: "color", default: "#4a1942" },
      { name: "sunColor", label: "Sun Color", type: "color", default: "#ff6b35" },
      { name: "waterColor", label: "Water", type: "color", default: "#1a3a4a" },
      { name: "speed", label: "Animation Speed", type: "range", default: 1, min: 0.1, max: 2, step: 0.1 },
      { name: "pixelSize", label: "Pixel Size", type: "range", default: 1, min: 0.5, max: 2, step: 0.1 },
      { name: "waveIntensity", label: "Wave Intensity", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
      { name: "starDensity", label: "Star Density", type: "range", default: 1, min: 0, max: 3, step: 0.1 },
      { name: "starShine", label: "Star Twinkle", type: "range", default: 1, min: 0.2, max: 3, step: 0.1 },
      { name: "shootingStars", label: "Shooting Stars", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
      { name: "timeOfDay", label: "Time of Day", type: "range", default: 0.5, min: 0, max: 1, step: 0.05 },
    ],
    get code() { return getShaderCode("pixel-art") },
    defaultProps: { skyColor1: "#1a0533", skyColor2: "#4a1942", sunColor: "#ff6b35", waterColor: "#1a3a4a", speed: 1, pixelSize: 1, waveIntensity: 1, starDensity: 1, starShine: 1, shootingStars: 1, timeOfDay: 0.5 },
  },
  {
    slug: "fluid-ink",
    name: "Fluid Ink",
    description: "Flowing ink with domain warping, swirls, and color bleeding.",
    tags: ["fluid", "organic", "smoke", "abstract", "flow"],
    author: "ShaderDrop",
    createdAt: "2025-01-16",
    uniforms: [
      { name: "color1", label: "Background", type: "color", default: "#0a0a1a" },
      { name: "color2", label: "Mid Color", type: "color", default: "#1a1a4e" },
      { name: "color3", label: "Highlight", type: "color", default: "#6a0dad" },
      { name: "speed", label: "Speed", type: "range", default: 1, min: 0.1, max: 2, step: 0.1 },
      { name: "complexity", label: "Complexity", type: "range", default: 1.5, min: 0.5, max: 3, step: 0.1 },
      { name: "flowSpeed", label: "Flow Speed", type: "range", default: 0.4, min: 0.1, max: 1, step: 0.05 },
      { name: "turbulence", label: "Turbulence", type: "range", default: 1, min: 0.2, max: 2, step: 0.1 },
      { name: "inkDensity", label: "Ink Density", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
      { name: "spread", label: "Spread", type: "range", default: 1, min: 0.2, max: 2, step: 0.1 },
      { name: "glow", label: "Glow", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
      { name: "zoom", label: "Zoom", type: "range", default: 1, min: 0.3, max: 3, step: 0.1 },
    ],
    get code() { return getShaderCode("fluid-ink") },
    defaultProps: { color1: "#0a0a1a", color2: "#1a1a4e", color3: "#6a0dad", speed: 1, complexity: 1.5, flowSpeed: 0.4, turbulence: 1, inkDensity: 1, spread: 1, glow: 1, zoom: 1 },
  },
  {
    slug: "aurora-mesh",
    name: "Aurora Mesh",
    description: "Triangular wave pattern with dynamic lighting and specular highlights.",
    tags: ["mesh", "triangles", "waves", "geometric", "tech"],
    author: "ShaderDrop",
    createdAt: "2025-01-16",
    uniforms: [
      { name: "baseColor", label: "Base Color", type: "color", default: "#0a0a12" },
      { name: "accentColor", label: "Accent/Light", type: "color", default: "#6366f1" },
      { name: "speed", label: "Animation Speed", type: "range", default: 1, min: 0.1, max: 2, step: 0.1 },
      { name: "scale", label: "Zoom", type: "range", default: 1, min: 0.5, max: 2, step: 0.1 },
      { name: "waveHeight", label: "Wave Height", type: "range", default: 1, min: 0.2, max: 2, step: 0.1 },
      { name: "lightIntensity", label: "Light Intensity", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
      { name: "specular", label: "Specular", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
    ],
    get code() { return getShaderCode("aurora-mesh") },
    defaultProps: { baseColor: "#0a0a12", accentColor: "#6366f1", speed: 1, scale: 1, waveHeight: 1, lightIntensity: 1, specular: 1 },
  },
  {
    slug: "wave-terrain",
    name: "Wave Terrain",
    description: "Raymarched terrain with triangular waves, fog, and camera movement.",
    tags: ["terrain", "waves", "perspective", "raymarching", "3d"],
    author: "ShaderDrop",
    createdAt: "2025-01-17",
    uniforms: [
      { name: "baseColor", label: "Terrain Color", type: "color", default: "#0a0a15" },
      { name: "accentColor", label: "Light Color", type: "color", default: "#8b5cf6" },
      { name: "skyColor", label: "Sky/Fog Color", type: "color", default: "#0a0612" },
      { name: "speed", label: "Animation Speed", type: "range", default: 1, min: 0.1, max: 2, step: 0.1 },
      { name: "scale", label: "Zoom", type: "range", default: 1, min: 0.5, max: 2, step: 0.1 },
      { name: "waveHeight", label: "Wave Height", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
      { name: "lightIntensity", label: "Light Intensity", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
      { name: "cameraHeight", label: "Camera Height", type: "range", default: 1, min: 0.5, max: 2, step: 0.1 },
      { name: "fogDensity", label: "Fog Density", type: "range", default: 1, min: 0, max: 3, step: 0.1 },
      { name: "gridSize", label: "Triangle Size", type: "range", default: 1.4, min: 0.5, max: 3, step: 0.1 },
      { name: "particleIntensity", label: "Particles", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
    ],
    get code() { return getShaderCode("wave-terrain") },
    defaultProps: { baseColor: "#0a0a15", accentColor: "#8b5cf6", skyColor: "#0a0612", speed: 1, scale: 1, waveHeight: 1, lightIntensity: 1, cameraHeight: 1, fogDensity: 1, gridSize: 1.4, particleIntensity: 1 },
  },
  {
    slug: "gradient-orbs",
    name: "Gradient Orbs",
    description: "Flowing gradient blobs with metaball blending and organic motion.",
    tags: ["gradient", "blobs", "smooth", "modern", "metaball"],
    author: "ShaderDrop",
    createdAt: "2025-01-17",
    uniforms: [
      { name: "color1", label: "Primary", type: "color", default: "#ff6b00" },
      { name: "color2", label: "Secondary", type: "color", default: "#ff0844" },
      { name: "color3", label: "Accent", type: "color", default: "#ffb700" },
      { name: "color4", label: "Highlight", type: "color", default: "#ff4500" },
      { name: "bgColor", label: "Background", type: "color", default: "#0a0a0a" },
      { name: "speed", label: "Speed", type: "range", default: 1, min: 0.1, max: 2, step: 0.1 },
      { name: "scale", label: "Scale", type: "range", default: 0.7, min: 0.3, max: 2, step: 0.1 },
      { name: "blur", label: "Softness", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
      { name: "intensity", label: "Intensity", type: "range", default: 1, min: 0.3, max: 1.5, step: 0.1 },
      { name: "glow", label: "Glow", type: "range", default: 1, min: 0, max: 2, step: 0.1 },
      { name: "distortion", label: "Distortion", type: "range", default: 0.5, min: 0, max: 2, step: 0.1 },
      { name: "chromaticAberration", label: "Chromatic", type: "range", default: 0, min: 0, max: 2, step: 0.1 },
      { name: "grain", label: "Grain", type: "range", default: 0.3, min: 0, max: 1, step: 0.1 },
      { name: "vignette", label: "Vignette", type: "range", default: 0.5, min: 0, max: 1.5, step: 0.1 },
      { name: "colorShift", label: "Color Shift", type: "range", default: 0.3, min: 0, max: 1, step: 0.1 },
      { name: "pulse", label: "Pulse", type: "range", default: 0.3, min: 0, max: 1, step: 0.1 },
      { name: "orbCount", label: "Orb Count", type: "range", default: 6, min: 2, max: 8, step: 1 },
    ],
    get code() { return getShaderCode("gradient-orbs") },
    defaultProps: { color1: "#ff6b00", color2: "#ff0844", color3: "#ffb700", color4: "#ff4500", bgColor: "#0a0a0a", speed: 1, scale: 0.7, blur: 1, intensity: 1, glow: 1, distortion: 0.5, chromaticAberration: 0, grain: 0.3, vignette: 0.5, colorShift: 0.3, pulse: 0.3, orbCount: 6 },
  },
  {
    slug: "silk-flow",
    name: "Silk Flow",
    description: "Smooth flowing gradients with soft color blending.",
    tags: ["gradient", "flow", "smooth", "elegant", "soft"],
    author: "ShaderDrop",
    createdAt: "2025-01-17",
    uniforms: [
      { name: "color1", label: "Color 1", type: "color", default: "#6366f1" },
      { name: "color2", label: "Color 2", type: "color", default: "#8b5cf6" },
      { name: "color3", label: "Color 3", type: "color", default: "#ec4899" },
      { name: "bgColor", label: "Background", type: "color", default: "#0f0f23" },
      { name: "speed", label: "Speed", type: "range", default: 1, min: 0.1, max: 2, step: 0.1 },
      { name: "scale", label: "Scale", type: "range", default: 1, min: 0.3, max: 2, step: 0.1 },
      { name: "softness", label: "Softness", type: "range", default: 0.5, min: 0, max: 1, step: 0.1 },
      { name: "intensity", label: "Intensity", type: "range", default: 1, min: 0.3, max: 1.5, step: 0.1 },
    ],
    get code() { return getShaderCode("silk-flow") },
    defaultProps: { color1: "#6366f1", color2: "#8b5cf6", color3: "#ec4899", bgColor: "#0f0f23", speed: 1, scale: 1, softness: 0.5, intensity: 1 },
  },
]

export function getShaderBySlug(slug: string): Shader | undefined {
  return shaders.find((s) => s.slug === slug)
}

export function getAllShaders(): Shader[] {
  return shaders
}

export function getShadersByTag(tag: string): Shader[] {
  return shaders.filter((s) => s.tags.includes(tag))
}

export function getAllTags(): string[] {
  const tags = new Set<string>()
  shaders.forEach((s) => s.tags.forEach((t) => tags.add(t)))
  return Array.from(tags).sort()
}
